/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GalleryCollectionIdRouteImport } from './routes/gallery/$collectionId'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as accountWalletIdIndexRouteImport } from './routes/(account)/$walletId/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCollectionIdRoute = GalleryCollectionIdRouteImport.update({
  id: '/gallery/$collectionId',
  path: '/gallery/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const accountWalletIdIndexRoute = accountWalletIdIndexRouteImport.update({
  id: '/(account)/$walletId/',
  path: '/$walletId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/gallery/$collectionId': typeof GalleryCollectionIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/$walletId': typeof accountWalletIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/gallery/$collectionId': typeof GalleryCollectionIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/$walletId': typeof accountWalletIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/gallery/$collectionId': typeof GalleryCollectionIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/(account)/$walletId/': typeof accountWalletIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/gallery/$collectionId'
    | '/gallery'
    | '/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/gallery/$collectionId'
    | '/gallery'
    | '/$walletId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/gallery/$collectionId'
    | '/gallery/'
    | '/(account)/$walletId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  GalleryCollectionIdRoute: typeof GalleryCollectionIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  accountWalletIdIndexRoute: typeof accountWalletIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$collectionId': {
      id: '/gallery/$collectionId'
      path: '/gallery/$collectionId'
      fullPath: '/gallery/$collectionId'
      preLoaderRoute: typeof GalleryCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/$walletId/': {
      id: '/(account)/$walletId/'
      path: '/$walletId'
      fullPath: '/$walletId'
      preLoaderRoute: typeof accountWalletIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  GalleryCollectionIdRoute: GalleryCollectionIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  accountWalletIdIndexRoute: accountWalletIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
